/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import com.sun.deploy.util.SessionState.Client;
import java.io.File;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author vikas
 */
public class language extends javax.swing.JFrame {

    /**
     * Creates new form language
     */
    public language() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        next_but = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jLabel1.setText("NAME");

        jLabel2.setText("PHONE NUMBER");

        jLabel3.setText("EMAIL");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        next_but.setText("NEXT");
        next_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(151, 151, 151)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(next_but)))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165)
                .addComponent(next_but)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel4, "card5");

        jComboBox1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azerbaijan", "Albanian", "Amharic", "English", "Arabic", "Armenian", "Afrikaans", "Basque", "Bashkir", "Belarusian", "Bengali", "Burmese", "Bulgarian", "Bosnian", "Welsh", "Hungarian", "Vietnamese", "Haitian (Creole)", "Galician", "Dutch", "Hill Mari", "Greek", "Georgian", "Gujarati", "Danish", "Hebrew", "Yiddish", "Indonesian", "Irish", "Italian", "Icelandic", "Spanish", "Kazakh", "Kannada", "Catalan", "Kyrgyz", "Chinese", "Korean", "Xhosa", "Khmer", "Laotian", "Latin", "Latvian", "Lithuanian", "Luxembourgish", "Malagasy", "Malay", "Malayalam", "Maltese", "Macedonian", "Maori", "Marathi", "Mari", "Mongolian", "German", "Nepali", "Norwegian", "Punjabi", "Papiamento", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Cebuano", "Serbian", "Sinhala", "Slovakian", "Slovenian", "Swahili", "Sundanese", "Tajik", "Thai", "Tagalog", "Tamil", "Tatar", "Telugu", "Turkish", "Udmurt", "Uzbek", "Ukrainian", "Urdu", "Finnish", "French", "Hindi", "Croatian", "Czech", "Swedish", "Scottish", "Estonian", "Esperanto", "Javanese", "Japanese" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azerbaijan", "Albanian", "Amharic", "English", "Arabic", "Armenian", "Afrikaans", "Basque", "Bashkir", "Belarusian", "Bengali", "Burmese", "Bulgarian", "Bosnian", "Welsh", "Hungarian", "Vietnamese", "Haitian (Creole)", "Galician", "Dutch", "Hill Mari", "Greek", "Georgian", "Gujarati", "Danish", "Hebrew", "Yiddish", "Indonesian", "Irish", "Italian", "Icelandic", "Spanish", "Kazakh", "Kannada", "Catalan", "Kyrgyz", "Chinese", "Korean", "Xhosa", "Khmer", "Laotian", "Latin", "Latvian", "Lithuanian", "Luxembourgish", "Malagasy", "Malay", "Malayalam", "Maltese", "Macedonian", "Maori", "Marathi", "Mari", "Mongolian", "German", "Nepali", "Norwegian", "Punjabi", "Papiamento", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Cebuano", "Serbian", "Sinhala", "Slovakian", "Slovenian", "Swahili", "Sundanese", "Tajik", "Thai", "Tagalog", "Tamil", "Tatar", "Telugu", "Turkish", "Udmurt", "Uzbek", "Ukrainian", "Urdu", "Finnish", "French", "Hindi", "Croatian", "Czech", "Swedish", "Scottish", "Estonian", "Esperanto", "Javanese", "Japanese" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("CONVERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton4.setText("PRINT SUMMARY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(408, 408, 408))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(109, 109, 109))
        );

        jLayeredPane1.add(jPanel1, "card2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("summary");

        jLabel5.setText("SERIAL_NO");

        jLabel6.setText("NAME");

        jLabel7.setText("E-MAIL");

        jLabel8.setText("PHONE NUMBER");

        jLabel10.setText("CONVERTED FROM");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel11.setText("CONVERTED TO");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jLabel9.setText("CONVERTED TO");

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGap(421, 421, 421)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8))
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)))
                                    .addComponent(jLabel11))
                                .addGap(250, 250, 250)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField3)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jButton2)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(66, 66, 66)
                .addComponent(jButton2)
                .addGap(72, 72, 72)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel5, "card6");

        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(50, 0, 0));
        jButton3.setText("CLICK HERE TO MOVE AHEAD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );

        jLayeredPane1.add(jPanel3, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String inline = "";

try {

	String key = "key=trnsl.1.1.20220215T113000Z.532cc2d04ae817f0.8746815d168b0ec9689736ec986901a135212ff1";
	String inputText = jTextArea1.getText();
	inputText = inputText.replaceAll(" ", "%20");

	String firstLan = "";
	int x = this.jComboBox1.getSelectedIndex();
	
	switch (x) {
	case 0:
		firstLan = "az";
		break;
	case 1:
		firstLan = "sq";
		break;
	case 2:
		firstLan = "am";
		break;
	case 3:
		firstLan = "en";
		break;
	case 4:
		firstLan = "ar";
		break;
	case 5:
		firstLan = "hy";
		break;
	case 6:
		firstLan = "af";
		break;
	case 7:
		firstLan = "eu";
		break;
	case 8:
		firstLan = "ba";
		break;
	case 9:
		firstLan = "be";
		break;
	case 10:
		firstLan = "bn";
		break;
	case 11:
		firstLan = "my";
		break;
	case 12:
		firstLan = "bg";
		break;
	case 13:
		firstLan = "bs";
		break;
	case 14:
		firstLan = "cy";
		break;
	case 15:
		firstLan = "hu";
		break;
	case 16:
		firstLan = "vi";
		break;
	case 17:
		firstLan = "ht";
		break;
	case 18:
		firstLan = "gl";
		break;
	case 19:
		firstLan = "nl";
		break;
	case 20:
		firstLan = "mrj";
		break;
	case 21:
		firstLan = "el";
		break;
	case 22:
		firstLan = "ka";
		break;
	case 23:
		firstLan = "gu";
		break;
	case 24:
		firstLan = "da";
		break;
	case 25:
		firstLan = "he";
		break;
	case 26:
		firstLan = "yi";
		break;
	case 27:
		firstLan = "id";
		break;
	case 28:
		firstLan = "ga";
		break;
	case 29:
		firstLan = "it";
		break;
	case 30:
		firstLan = "is";
		break;
	case 31:
		firstLan = "es";
		break;
	case 32:
		firstLan = "kk";
		break;
	case 33:
		firstLan = "kn";
		break;
	case 34:
		firstLan = "ca";
		break;
	case 35:
		firstLan = "ky";
		break;
	case 36:
		firstLan = "zh";
		break;
	case 37:
		firstLan = "ko";
		break;
	case 38:
		firstLan = "xh";
		break;
	case 39:
		firstLan = "km";
		break;
	case 40:
		firstLan = "lo";
		break;
	case 41:
		firstLan = "la";
		break;
	case 42:
		firstLan = "lv";
		break;
	case 43:
		firstLan = "lt";
		break;
	case 44:
		firstLan = "lb";
		break;
	case 45:
		firstLan = "mg";
		break;
	case 46:
		firstLan = "ms";
		break;
	case 47:
		firstLan = "ml";
		break;
	case 48:
		firstLan = "mt";
		break;
	case 49:
		firstLan = "mk";
		break;
	case 50:
		firstLan = "mi";
		break;
	case 51:
		firstLan = "mr";
		break;
	case 52:
		firstLan = "mhr";
		break;
	case 53:
		firstLan = "mn";
		break;
	case 54:
		firstLan = "de";
		break;
	case 55:
		firstLan = "ne";
		break;
	case 56:
		firstLan = "no";
		break;
	case 57:
		firstLan = "pa";
		break;
	case 58:
		firstLan = "pap";
		break;
	case 59:
		firstLan = "fa";
		break;
	case 60:
		firstLan = "pl";
		break;
	case 61:
		firstLan = "pt";
		break;
	case 62:
		firstLan = "ro";
		break;
	case 63:
		firstLan = "ru";
		break;
	case 64:
		firstLan = "ceb";
		break;
	case 65:
		firstLan = "sr";
		break;
	case 66:
		firstLan = "si";
		break;
	case 67:
		firstLan = "sk";
		break;
	case 68:
		firstLan = "sl";
		break;
	case 69:
		firstLan = "sw";
		break;
	case 70:
		firstLan = "su";
		break;
	case 71:
		firstLan = "tg";
		break;
	case 72:
		firstLan = "th";
		break;
	case 73:
		firstLan = "tl";
		break;
	case 74:
		firstLan = "ta";
		break;
	case 75:
		firstLan = "tt";
		break;
	case 76:
		firstLan = "te";
		break;
	case 77:
		firstLan = "tr";
		break;
	case 78:
		firstLan = "udm";
		break;
	case 79:
		firstLan = "uz";
		break;
	case 80:
		firstLan = "uk";
		break;
	case 81:
		firstLan = "ur";
		break;
	case 82:
		firstLan = "fi";
		break;
	case 83:
		firstLan = "fr";
		break;
	case 84:
		firstLan = "hi";
		break;
	case 85:
		firstLan = "hr";
		break;
	case 86:
		firstLan = "cs";
		break;
	case 87:
		firstLan = "sv";
		break;
	case 88:
		firstLan = "gd";
		break;
	case 89:
		firstLan = "et";
		break;
	case 90:
		firstLan = "eo";
		break;
	case 91:
		firstLan = "jv";
		break;
	case 92:
		firstLan = "ja";
		break;

	default:
		break;

	}

	String secLan = "";
	int y = this.jComboBox2.getSelectedIndex();
	switch (y) {
	case 0:
		secLan = "az";
		break;
	case 1:
		secLan = "sq";
		break;
	case 2:
		secLan = "am";
		break;
	case 3:
		secLan = "en";
		break;
	case 4:
		secLan = "ar";
		break;
	case 5:
		secLan = "hy";
		break;
	case 6:
		secLan = "af";
		break;
	case 7:
		secLan = "eu";
		break;
	case 8:
		secLan = "ba";
		break;
	case 9:
		secLan = "be";
		break;
	case 10:
		secLan = "bn";
		break;
	case 11:
		secLan = "my";
		break;
	case 12:
		secLan = "bg";
		break;
	case 13:
		secLan = "bs";
		break;
	case 14:
		secLan = "cy";
		break;
	case 15:
		secLan = "hu";
		break;
	case 16:
		secLan = "vi";
		break;
	case 17:
		secLan = "ht";
		break;
	case 18:
		secLan = "gl";
		break;
	case 19:
		secLan = "nl";
		break;
	case 20:
		secLan = "mrj";
		break;
	case 21:
		secLan = "el";
		break;
	case 22:
		secLan = "ka";
		break;
	case 23:
		secLan = "gu";
		break;
	case 24:
		secLan = "da";
		break;
	case 25:
		secLan = "he";
		break;
	case 26:
		secLan = "yi";
		break;
	case 27:
		secLan = "id";
		break;
	case 28:
		secLan = "ga";
		break;
	case 29:
		secLan = "it";
		break;
	case 30:
		secLan = "is";
		break;
	case 31:
		secLan = "es";
		break;
	case 32:
		secLan = "kk";
		break;
	case 33:
		secLan = "kn";
		break;
	case 34:
		secLan = "ca";
		break;
	case 35:
		secLan = "ky";
		break;
	case 36:
		secLan = "zh";
		break;
	case 37:
		secLan = "ko";
		break;
	case 38:
		secLan = "xh";
		break;
	case 39:
		secLan = "km";
		break;
	case 40:
		secLan = "lo";
		break;
	case 41:
		secLan = "la";
		break;
	case 42:
		secLan = "lv";
		break;
	case 43:
		secLan = "lt";
		break;
	case 44:
		secLan = "lb";
		break;
	case 45:
		secLan = "mg";
		break;
	case 46:
		secLan = "ms";
		break;
	case 47:
		secLan = "ml";
		break;
	case 48:
		secLan = "mt";
		break;
	case 49:
		secLan = "mk";
		break;
	case 50:
		secLan = "mi";
		break;
	case 51:
		secLan = "mr";
		break;
	case 52:
		secLan = "mhr";
		break;
	case 53:
		secLan = "mn";
		break;
	case 54:
		secLan = "de";
		break;
	case 55:
		secLan = "ne";
		break;
	case 56:
		secLan = "no";
		break;
	case 57:
		secLan = "pa";
		break;
	case 58:
		secLan = "pap";
		break;
	case 59:
		secLan = "fa";
		break;
	case 60:
		secLan = "pl";
		break;
	case 61:
		secLan = "pt";
		break;
	case 62:
		secLan = "ro";
		break;
	case 63:
		secLan = "ru";
		break;
	case 64:
		secLan = "ceb";
		break;
	case 65:
		secLan = "sr";
		break;
	case 66:
		secLan = "si";
		break;
	case 67:
		secLan = "sk";
		break;
	case 68:
		secLan = "sl";
		break;
	case 69:
		secLan = "sw";
		break;
	case 70:
		secLan = "su";
		break;
	case 71:
		secLan = "tg";
		break;
	case 72:
		secLan = "th";
		break;
	case 73:
		secLan = "tl";
		break;
	case 74:
		secLan = "ta";
		break;
	case 75:
		secLan = "tt";
		break;
	case 76:
		secLan = "te";
		break;
	case 77:
		secLan = "tr";
		break;
	case 78:
		secLan = "udm";
		break;
	case 79:
		secLan = "uz";
		break;
	case 80:
		secLan = "uk";
		break;
	case 81:
		secLan = "ur";
		break;
	case 82:
		secLan = "fi";
		break;
	case 83:
		secLan = "fr";
		break;
	case 84:
		secLan = "hi";
		break;
	case 85:
		secLan = "hr";
		break;
	case 86:
		secLan = "cs";
		break;
	case 87:
		secLan = "sv";
		break;
	case 88:
		secLan = "gd";
		break;
	case 89:
		secLan = "et";
		break;
	case 90:
		secLan = "eo";
		break;
	case 91:
		secLan = "jv";
		break;
	case 92:
		secLan = "ja";
		break;

	default:
		break;
	}
        jTextField11.setText(jComboBox1.getSelectedItem().toString());
        jTextField3.setText(jComboBox2.getSelectedItem().toString());

	System.err.println(firstLan);

	URL url = new URL("https://translate.yandex.net/api/v1.5/tr.json/translate?" + key + "&" + "text=" + inputText + "&" + "lang=" + firstLan + "-" + secLan + "&[format=[plain]&[options=1]&[callback=inline]");

	//Parse URL into HttpURLConnection in order to open the connection in order to get the JSON data
	HttpURLConnection conn = (HttpURLConnection) url.openConnection();
	//Set the request to GET or POST as per the requirements
	conn.setRequestMethod("GET");
	//Use the connect method to create the connection bridge
	conn.connect();
	//Get the response status of the Rest API
	int responsecode = conn.getResponseCode();
	System.out.println("Response code is: " + responsecode);
	System.out.println(url);

              try ( //process of getting the JSON data
                      Scanner sc = new Scanner(url.openStream())) {
                  while (sc.hasNext())
                      
                  {
                      
                      inline += sc.nextLine();
                      
                  }
                  
                  System.out.println("\nJSON data in string format");
                  
                  System.out.println(inline);
              }

	//Parse the JSON data present in the string format
	JSONParser parse = new JSONParser();

	//Type caste the parsed json data in json object
	JSONObject jobj = (JSONObject) parse.parse(inline);

	//Store the JSON object in JSON array as objects (For level 1 array element i.e Results)
	JSONArray jsonarr_1 = (JSONArray) jobj.get("text");

	String str_data1 = (String) jsonarr_1.get(0);
	System.out.println(str_data1);
	jTextArea2.setText(str_data1);

	conn.disconnect();
}

catch(MalformedURLException ex) {
	Logger.getLogger(language.class.getName()).log(Level.SEVERE, null, ex);
} catch(IOException | ParseException ex) {
	Logger.getLogger(language.class.getName()).log(Level.SEVERE, null, ex);
}
        
			
				
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
                switch (jComboBox1.getSelectedIndex()) {
            case 0:
                
               
                break;
            case 1:
                
                    break;
                }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
         switch (jComboBox2.getSelectedIndex()) {
            case 0:
               
                break;
            case 1:
                
                    break;
                }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jPanel4.setVisible(true);
       jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void next_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_butActionPerformed
       jPanel4.setVisible(false);
       jPanel1.setVisible(true);
        
        try {
            String name=jTextField1.getText();
            String phone_no=jTextField2.getText();
            String email=jTextField5.getText();
            
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","")) {
                String query="insert into data(name,email,phone_no) values(?,?,?)";
                PreparedStatement st= c.prepareStatement(query);
                st.setString(1,name);
                st.setString(2,email);
                st.setString(3,phone_no);
                
                st.execute();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(language.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
       
    }//GEN-LAST:event_next_butActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jPanel1.setVisible(false);
       jPanel5.setVisible(true);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
            Statement st=c.createStatement();
            String query="SELECT * FROM data WHERE serial_no=(SELECT max(serial_no) FROM data);";
             ResultSet rs=st.executeQuery(query);
            rs.next();
            
                jTextField6.setText(rs.getString(1));
                jTextField7.setText(rs.getString(2));
                jTextField8.setText(rs.getString(3));
                jTextField9.setText(rs.getString(4));
                
           
            
            
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(language.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new language().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton next_but;
    // End of variables declaration//GEN-END:variables

    private static class ClientImpl implements Client {

        public ClientImpl() {
        }

        private ClientImpl(String kfBJYRwXPu6lSo98wDRyW01kv8oMCWOteaEyILwf7) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void importState(File file) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void exportState(File file) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
